name: build_develop_version

on:
  push:
    branches: [ "dev" ]

permissions:
  contents: write # 赋予修改 Release 的权限

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download and setup NVGT compiler
      run: |
        set -e
        mkdir -p nvgt
        curl -L https://github.com/samtupy/nvgt/releases/download/latest/nvgt_0.90.0_dev.tar.gz -o nvgt.tar.gz
        tar -xzf nvgt.tar.gz -C nvgt
        rm nvgt.tar.gz
        chmod +x $GITHUB_WORKSPACE/nvgt/nvgt
        echo "${{ github.workspace }}/nvgt" >> $GITHUB_PATH

#    - name: build windows client
#      run: |
#        nvgt tk.nvgt --compile-debug -pwindows

    - name: build windows server
      run: |
        nvgt --compile-debug -pwindows "$GITHUB_WORKSPACE/server/tkserver.nvgt"

    - name: build linux server
      run: |
        nvgt --compile-debug -p linux "$GITHUB_WORKSPACE/server/tkserver.nvgt"

    - name: Update Latest Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: "latest-develop-version"
        name: "latest develop version"
        body: |
          ${{ github.sha }}
          ${{ github.event.head_commit.message }}
        prerelease: true
        files: |
          tkserver.zip
          tkserver.tar.gz
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
